services:
  wordpress:
    build:
      context: .docker/wordpress
      args:
        VERSION_WORDPRESS: ${VERSION_WORDPRESS:-6.7}
        VERSION_PHP: ${VERSION_PHP:-8.3}
    restart: unless-stopped
    volumes:
      - ./volumes/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mariadb}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-root}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=host.docker.internal start_with_request=yes}
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./volumes/wordpress:/var/www/html:ro
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    environment:
      - DEFAULT_HOST
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST

  mariadb:
    profiles:
      - dev
    build:
      context: .docker/mariadb
    volumes:
      - ./volumes/mariadb/dump:/docker-entrypoint-initdb.d
      - ./volumes/mariadb/data:/var/lib/mysql
    restart: always
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - MARIADB_USER=${MARIADB_USER:-root}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-root}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-wordpress}
