version: "3.7"

# networks:
#   reverse-proxy:
#     external: true
#     name: reverse-proxy
#   mysql:
#     external: true
#     name: mysql

services:
  php56:
    build:
      context: .docker/php56
    volumes:
      - ./volumes/site/www:/var/www/html
      - ./.docker/php56/config/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php56/config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - .php5.env
    ports:
      - 80:80
    # networks:
    #   - reverse-proxy
    #   - mysql
  wordpress:
    build:
      context: .docker/wordpress
    volumes:
      - ./volumes/wordpress:/var/www/html
    env_file:
      - .env
    ports:
      - 8080:80
    # networks:
    #   - reverse-proxy
    #   - mysql
  db:
   build:
     context: .docker/mysql
   volumes:
     # - ./.docker/mysql/conf:/etc/mysql/conf.d
     - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
     - ./volumes/mysql/data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=root
   ports:
     - 3306:3306
   restart: always
  #mailhog:
  #  image: blueimp/mailhog
  #  ports:
  #    - 8025:8025