version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  mysql:
    external: true
    name: mysql
  internal:
    driver: bridge

services:
  wordpress:
    build:
      context: .docker/wordpress
    restart: unless-stopped
    volumes:
      - ./volumes/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - mysql
      - internal
  nginx:
    depends_on:
      - wordpress
    image: nginx
    restart: unless-stopped
    volumes:
      - ./volumes/wordpress:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - reverse-proxy
      - internal
    ports:
      - 80:80
    environment:
      - DEFAULT_HOST
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
  mysql:
   build:
     context: .docker/mysql
   volumes:
     - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
     - ./volumes/mysql/data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=root
   ports:
     - 3306:3306
   restart: always
   networks:
     - mysql
