version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  mariadb:
    external: true
    name: mariadb
  internal:
    driver: bridge

services:
  wordpress:
    depends_on:
      - mariadb
    build:
      context: .docker/wordpress
      args:
        VERSION_WORDPRESS: ${VERSION_WORDPRESS:-6.4}
        VERSION_PHP: ${VERSION_PHP:-8.3}
    restart: unless-stopped
    volumes:
      - ./volumes/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - mariadb
      - internal

  nginx:
    depends_on:
      - wordpress
    image: nginx
    restart: unless-stopped
    volumes:
      - ./volumes/wordpress:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - reverse-proxy
      - internal
    ports:
      - 80:80
    environment:
      - DEFAULT_HOST
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST

  mariadb:
    build:
      context: .docker/mariadb
    env_file:
      - .env
    volumes:
      - ./volumes/mariadb/dump:/docker-entrypoint-initdb.d
      - ./volumes/mariadb/data:/var/lib/mariadb
    restart: always
    networks:
      - mariadb
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
