services:
  wordpress:
    extends:
      file: common-services.yml
      service: wordpress

  nginx:
    extends:
      file: common-services.yml
      service: nginx
    environment:
      - DEFAULT_HOST
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
