version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  mysql:
    external: true
    name: mysql

services:
  php56:
    build:
      context: .docker/php56
    volumes:
      - ./volumes/site/www:/var/www/html
      - ./.docker/php56/config/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php56/config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - reverse-proxy
      - mysql
    environment:
      - XDEBUG_CONFIG=remote_host=172.18.0.1 remote_enable=1
      - DEFAULT_HOST=homolog.amperj.org
      - VIRTUAL_HOST=homolog.amperj.org
      - LETSENCRYPT_HOST=homolog.amperj.org
      - LETSENCRYPT_EMAIL=adm@librecode.coop
